apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: microservices-app
data:
  config.js: |
    window.APP_CONFIG = {
      VITE_API_BASE_URL: '/api/v1',
      VITE_MINIO_BASE_URL: '/minio',
      VITE_API_CONTENT_ABOUT: '/about',
      VITE_API_CONTENT_TECH: '/tech',
      VITE_API_CONTENT_CERTIFICATES: '/certificates',
      VITE_API_CONTENT_PUBLICATIONS: '/publications',
      VITE_API_CONTENT_PROJECTS: '/projects',
      VITE_API_CONTENT_COMMENTS: '/comments',
      VITE_API_AUTH_LOGIN: '/login',
      VITE_API_AUTH_REGISTER: '/register',
      VITE_API_AUTH_LOGOUT: '/logout',
      VITE_API_AUTH_REFRESH: '/refresh',
      VITE_API_AUTH_VERIFY: '/verify',
      VITE_API_AUTH_CHECK: '/check-auth',
      VITE_API_TIMEOUT: '10000'
    }