apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: microservices-app
data:
  kraft.properties: |
    # Kafka KRaft Configuration
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@kafka-controller-0.kafka-controller:9093,2@kafka-controller-1.kafka-controller:9093,3@kafka-controller-2.kafka-controller:9093
    listeners=PLAINTEXT://:19092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka-broker-0.kafka-broker:19092
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT
    listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    log.dirs=/opt/kafka/data
    num.partitions=1
    default.replication.factor=3
    min.insync.replicas=2
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2