apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices-app
type: Opaque
stringData:
  # =====================
  # SECRETS
  # =====================
  SECRET_KEY: "c761fd5cd80df51276932a6a044502b1404ab945a694c1234c56e33f06b780c1"
  ADMIN_PASSWORD: "1234567"

  # =====================
  # EMAIL SECRETS
  # =====================
  SMTP_USERNAME: "my.personalsite@yandex.ru"
  SMTP_PASSWORD: "idkgnclyfdpatjoi"
  SMTP_FROM: "my.personalsite@yandex.ru"

  # =====================
  # OBJECT STORAGE SECRETS
  # =====================
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"

  # =====================
  # DATABASE PASSWORDS
  # =====================
  POSTGRES_PASSWORD: "postgres"
  REDIS_PASSWORD: "secure_password"
  CONTENT_ADMIN_MONGO_ROOT_PASSWORD: "securepassword123"
  AUTH_ADMIN_MONGO_ROOT_PASSWORD: "securepassword123"
  NOTIFICATION_ADMIN_MONGO_ROOT_PASSWORD: "securepassword123"

  # =====================
  # DATABASE URLS WITH ROOT CREDENTIALS
  # =====================
  GRPC_CONTENT_MONGODB_URL: "mongodb://admin:securepassword123@content-db:27017/content_db?authSource=admin"
  GRPC_AUTH_MONGODB_URL: "mongodb://admin:securepassword123@auth-db:27017/auth_db?authSource=admin"
  NOTIFICATION_SERVICE_MONGODB_URL: "mongodb://admin:securepassword123@notification-db:27017/notification_db?authSource=admin"
  CONTENT_ADMIN_MONGODB_URL: "mongodb://admin:securepassword123@content-db:27017/content_db?authSource=admin"
  AUTH_ADMIN_MONGODB_URL: "mongodb://admin:securepassword123@auth-db:27017/auth_db?authSource=admin"
  NOTIFICATION_ADMIN_MONGODB_URL: "mongodb://admin:securepassword123@notification-db:27017/notification_db?authSource=admin"
  COMMENTS_ADMIN_POSTGRES_DB_URL: "postgresql+asyncpg://postgres:postgres@comments-db:5432/comments_db"